# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf44803f3cddbb8ed3a40259cba2a5f118766521b60a380812ecfbd18ffcc6f17236d6eb1f7a7bbe6e5e1974cb7f28bd9804488eca6de7a6708375b8038eccba

test:
  secret_key_base: 1bd04437d217da14ad98e74a6d5e02f7633b6b03cb8b2ccf06b391dc4c5df70c25bef81e0ae876714f6de098594d11572a0a6131635d4d0916c69b858b02b079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
